package gomdare

type DirectMessage struct {
	CreatedAt string `json:"created_at"`
	Entities  struct {
		Hashtags     []interface{} `json:"hashtags"`
		Urls         []interface{} `json:"urls"`
		UserMentions []interface{} `json:"user_mentions"`
	} `json:"entities"`
	ID        int    `json:"id"`
	IdStr     string `json:"id_str"`
	Recipient struct {
		ContributorsEnabled            bool        `json:"contributors_enabled"`
		CreatedAt                      string      `json:"created_at"`
		DefaultProfile                 bool        `json:"default_profile"`
		DefaultProfileImage            bool        `json:"default_profile_image"`
		Description                    string      `json:"description"`
		FavouritesCount                int         `json:"favourites_count"`
		FollowRequestSent              bool        `json:"follow_request_sent"`
		FollowersCount                 int         `json:"followers_count"`
		Following                      bool        `json:"following"`
		FriendsCount                   int         `json:"friends_count"`
		GeoEnabled                     bool        `json:"geo_enabled"`
		ID                             int         `json:"id"`
		IdStr                          string      `json:"id_str"`
		IsTranslator                   bool        `json:"is_translator"`
		Lang                           string      `json:"lang"`
		ListedCount                    int         `json:"listed_count"`
		Location                       string      `json:"location"`
		Name                           string      `json:"name"`
		Notifications                  bool        `json:"notifications"`
		ProfileBackgroundColor         string      `json:"profile_background_color"`
		ProfileBackgroundImageURL      string      `json:"profile_background_image_url"`
		ProfileBackgroundImageUrlHttps string      `json:"profile_background_image_url_https"`
		ProfileBackgroundTile          bool        `json:"profile_background_tile"`
		ProfileImageURL                string      `json:"profile_image_url"`
		ProfileImageUrlHttps           string      `json:"profile_image_url_https"`
		ProfileLinkColor               string      `json:"profile_link_color"`
		ProfileSidebarBorderColor      string      `json:"profile_sidebar_border_color"`
		ProfileSidebarFillColor        string      `json:"profile_sidebar_fill_color"`
		ProfileTextColor               string      `json:"profile_text_color"`
		ProfileUseBackgroundImage      bool        `json:"profile_use_background_image"`
		Protected                      bool        `json:"protected"`
		ScreenName                     string      `json:"screen_name"`
		ShowAllInlineMedia             bool        `json:"show_all_inline_media"`
		StatusesCount                  int         `json:"statuses_count"`
		TimeZone                       string      `json:"time_zone"`
		URL                            interface{} `json:"url"`
		UtcOffset                      int         `json:"utc_offset"`
		Verified                       bool        `json:"verified"`
	} `json:"recipient"`
	RecipientID         int    `json:"recipient_id"`
	RecipientScreenName string `json:"recipient_screen_name"`
	Sender              struct {
		ContributorsEnabled            bool   `json:"contributors_enabled"`
		CreatedAt                      string `json:"created_at"`
		DefaultProfile                 bool   `json:"default_profile"`
		DefaultProfileImage            bool   `json:"default_profile_image"`
		Description                    string `json:"description"`
		FavouritesCount                int    `json:"favourites_count"`
		FollowRequestSent              bool   `json:"follow_request_sent"`
		FollowersCount                 int    `json:"followers_count"`
		Following                      bool   `json:"following"`
		FriendsCount                   int    `json:"friends_count"`
		GeoEnabled                     bool   `json:"geo_enabled"`
		ID                             int    `json:"id"`
		IdStr                          string `json:"id_str"`
		IsTranslator                   bool   `json:"is_translator"`
		Lang                           string `json:"lang"`
		ListedCount                    int    `json:"listed_count"`
		Location                       string `json:"location"`
		Name                           string `json:"name"`
		Notifications                  bool   `json:"notifications"`
		ProfileBackgroundColor         string `json:"profile_background_color"`
		ProfileBackgroundImageURL      string `json:"profile_background_image_url"`
		ProfileBackgroundImageUrlHttps string `json:"profile_background_image_url_https"`
		ProfileBackgroundTile          bool   `json:"profile_background_tile"`
		ProfileImageURL                string `json:"profile_image_url"`
		ProfileImageUrlHttps           string `json:"profile_image_url_https"`
		ProfileLinkColor               string `json:"profile_link_color"`
		ProfileSidebarBorderColor      string `json:"profile_sidebar_border_color"`
		ProfileSidebarFillColor        string `json:"profile_sidebar_fill_color"`
		ProfileTextColor               string `json:"profile_text_color"`
		ProfileUseBackgroundImage      bool   `json:"profile_use_background_image"`
		Protected                      bool   `json:"protected"`
		ScreenName                     string `json:"screen_name"`
		ShowAllInlineMedia             bool   `json:"show_all_inline_media"`
		StatusesCount                  int    `json:"statuses_count"`
		TimeZone                       string `json:"time_zone"`
		URL                            string `json:"url"`
		UtcOffset                      int    `json:"utc_offset"`
		Verified                       bool   `json:"verified"`
	} `json:"sender"`
	SenderID         int    `json:"sender_id"`
	SenderScreenName string `json:"sender_screen_name"`
	Text             string `json:"text"`
}
